nodes: # List of nodes
  # Each node contains the following information
  - name: "A" # Name of the node
    ip_address: "192.168.1.1" # IP Address of the node
    mac_address: "aa:aa:aa:aa:aa:aa" # MAC Address of the node
    queries: # ARP Requests the Node performs. It is a list of IPs
      - "192.168.1.2"
      - "192.168.1.3"
      - "192.168.1.4"
      - "192.168.1.5"
      - "192.168.1.6"
      - "192.168.1.7"
      - "192.168.1.8"
      - "192.168.1.9"
      - "192.168.1.10"
  - name: "B"
    ip_address: "192.168.1.2"
    mac_address: "bb:bb:bb:bb:bb:bb"
    queries:
      - "192.168.1.3"
      - "192.168.1.4"
      - "192.168.1.5"
      - "192.168.1.6"
      - "192.168.1.7"
      - "192.168.1.8"
      - "192.168.1.9"
      - "192.168.1.10"
  - name: "C"
    ip_address: "192.168.1.3"
    mac_address: "cc:cc:cc:cc:cc:cc"
    queries:
      - "192.168.1.4"
      - "192.168.1.5"
      - "192.168.1.6"
      - "192.168.1.7"
      - "192.168.1.8"
      - "192.168.1.9"
      - "192.168.1.10"
  - name: "D"
    ip_address: "192.168.1.4"
    mac_address: "dd:dd:dd:dd:dd:dd"
    queries:
      - "192.168.1.5"
      - "192.168.1.6"
      - "192.168.1.7"
      - "192.168.1.8"
      - "192.168.1.9"
      - "192.168.1.10"
  - name: "E"
    ip_address: "192.168.1.5"
    mac_address: "ee:ee:ee:ee:ee:ee"
    queries:
      - "192.168.1.6"
      - "192.168.1.7"
      - "192.168.1.8"
      - "192.168.1.9"
      - "192.168.1.10"
  - name: "F"
    ip_address: "192.168.1.6"
    mac_address: "ff:ff:ff:ff:ff:ff"
    queries: 
      - "192.168.1.7"
      - "192.168.1.8"
      - "192.168.1.9"
      - "192.168.1.10"
  - name: "G"
    ip_address: "192.168.1.7"
    mac_address: "1a:1a:1a:1a:1a:1a"
    queries:
      - "192.168.1.8"
      - "192.168.1.9"
      - "192.168.1.10"
  - name: "H"
    ip_address: "192.168.1.8"
    mac_address: "1b:1b:1b:1b:1b:1b"
    queries:
      - "192.168.1.9"
      - "192.168.1.10"
  - name: "I"
    ip_address: "192.168.1.9"
    mac_address: "1c:1c:1c:1c:1c:1c"
    queries:
      - "192.168.1.10"
  - name: "J"
    ip_address: "192.168.1.10"
    mac_address: "1d:1d:1d:1d:1d:1d"
    queries: []
