nodes: # List of nodes
  # Each node contains the following information
  - name: "A" # Name of the node
    ip_address: "192.168.1.1" # IP Address of the node
    mac_address: "aa:aa:aa:aa:aa:aa" # MAC Address of the node
    queries: # ARP Requests the Node performs. It is a list of IPs
      - "192.168.1.2"
      - "192.168.1.3"
      - "192.168.1.4"
      - "192.168.1.5"
  - name: "B"
    ip_address: "192.168.1.2"
    mac_address: "bb:bb:bb:bb:bb:bb"
    queries:
      - "192.168.1.3"
      - "192.168.1.4"
      - "192.168.1.5"
  - name: "C"
    ip_address: "192.168.1.3"
    mac_address: "cc:cc:cc:cc:cc:cc"
    queries:
      - "192.168.1.4"
      - "192.168.1.5"
  - name: "D"
    ip_address: "192.168.1.4"
    mac_address: "dd:dd:dd:dd:dd:dd"
    queries:
      - "192.168.1.5"
  - name: "E"
    ip_address: "192.168.1.5"
    mac_address: "ee:ee:ee:ee:ee:ee"
    queries: []